/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CheckReactionSiteResponseInvalid { 
    type: CheckReactionSiteResponseInvalid.TypeEnum;
    message: string;
}
export namespace CheckReactionSiteResponseInvalid {
    export type TypeEnum = 'invalid_input' | '3d_gen' | 'no_reactive_nitrogens' | 'no_br_or_cl_in_el' | 'no_nitrogens_in_nuc' | 'br_in_nuc' | 'cl_in_nuc' | 'no_reaction_site';
    export const TypeEnum = {
        InvalidInput: 'invalid_input' as TypeEnum,
        _3dGen: '3d_gen' as TypeEnum,
        NoReactiveNitrogens: 'no_reactive_nitrogens' as TypeEnum,
        NoBrOrClInEl: 'no_br_or_cl_in_el' as TypeEnum,
        NoNitrogensInNuc: 'no_nitrogens_in_nuc' as TypeEnum,
        BrInNuc: 'br_in_nuc' as TypeEnum,
        ClInNuc: 'cl_in_nuc' as TypeEnum,
        NoReactionSite: 'no_reaction_site' as TypeEnum
    };
}


