/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChemicalAutoCompleteResponse { 
    name: string;
    smiles: string;
    inchi: string;
    inchi_key: string;
    metanetx_id: string;
    kegg_id: string;
    structure?: string;
}

