/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExportRequestBody { 
    jobId: string;
    cdxml: boolean;
    cdxml_filter: string;
    cdxml_selected_pages: Array<number>;
    csv: boolean;
    csv_filter: string;
    csv_molecules: Array<number>;
}

