/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An enumeration.
 */
export type JobType = 'clean' | 'chemscraper' | 'molli';

export const JobType = {
    Clean: 'clean' as JobType,
    Chemscraper: 'chemscraper' as JobType,
    Molli: 'molli' as JobType
};

