/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobStatus } from './jobStatus';


export interface JobUpdate { 
    job_id: string;
    run_id: number;
    time_start?: number;
    time_end?: number;
    job_info?: string;
    email?: string;
    image?: string;
    command?: string;
    phase?: JobStatus;
}
export namespace JobUpdate {
}


