/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Molecule { 
    id: number;
    flagged: boolean;
    doc_no: string;
    file_path: string;
    page_no: string;
    name?: string;
    SMILE: string;
    structure: string;
    minX: number;
    minY: number;
    width: number;
    height: number;
    PubChemCID?: string;
    molecularFormula?: string;
    molecularWeight?: string;
    chemicalSafety?: Array<string>;
    Description?: string;
    Location: string;
    OtherInstances: Array<string>;
    fingerprint: string;
}

