# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: chemscraper-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chemscraper-frontend
  template:
    metadata:
      labels:
        app: chemscraper-frontend
    spec:
      containers:
        - name: chemscraper-frontend
          image: {{ .Values.controller.image }}

          env:

          - name: JOB_MANAGER_API_HOSTNAME
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: hostname

          - name: JOB_MANAGER_API_BASEPATH
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: basePath

          - name: OAUTH_SIGNIN_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: signInUrl

          - name: OAUTH_SIGNOUT_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: signOutUrl

          - name: OAUTH_USERINFO_URL
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: userInfoUrl

          - name: ENABLE_HCAPTCHA
            valueFrom:
              configMapKeyRef:
                name: {{ .Release.Name }}-config
                key: enableHCaptcha



          ports:
            - containerPort: 80
          imagePullPolicy: Always
