# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: chemscraper-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chemscraper-frontend
  template:
    metadata:
      labels:
        app: chemscraper-frontend
    spec:
      containers:
        - name: chemscraper-frontend
          image: {{ .Values.controller.image }}

          ports:
            - containerPort: 80
          imagePullPolicy: Always
