apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: chemscraper-frontend
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
