export * from './chemScraper.service';
import { ChemScraperService } from './chemScraper.service';
export * from './default.service';
import { DefaultService } from './default.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './jobs.service';
import { JobsService } from './jobs.service';
export * from './molli.service';
import { MolliService } from './molli.service';
export * from './novostoic.service';
import { NovostoicService } from './novostoic.service';
export * from './reactionMiner.service';
import { ReactionMinerService } from './reactionMiner.service';
export * from './shared.service';
import { SharedService } from './shared.service';
export * from './somn.service';
import { SomnService } from './somn.service';
export const APIS = [ChemScraperService, DefaultService, FilesService, JobsService, MolliService, NovostoicService, ReactionMinerService, SharedService, SomnService];
